Prepare distribution on Modrinth
IntellectualSites/Plot2Dynmap pull request #152
Opened 2023-08-18 11:58 UTC by NotMyFault

I plan to merge the PR, once modrinth approved this project.

2023-08-18 13:28 UTC, SirYwell requested changes

2023-08-18 13:28 UTC, SirYwell commented on build.gradle.kts
> +    projectId.set("plothider")
```suggestion
    projectId.set("plot2dynmap")
```
I assume?

2023-08-18 13:29 UTC, NotMyFault commented on build.gradle.kts
> +    projectId.set("plothider")
Right, thanks!

2023-08-19 09:09 UTC, SirYwell approved these changes

2023-08-24 07:22 UTC, merged