Update to p2-v6/1.17
IntellectualSites/Plot2Dynmap pull request #36
Opened 2021-08-22 16:40 UTC by dordsor21

Tested and works for me (might take a minute or two to update on the dynmap)

2021-08-22 17:19 UTC, NotMyFault requested changes
Imo the markers should match the actual data from `/plot info`.
![](https://i.imgur.com/kcQaVoR.png)
![](https://i.imgur.com/23GnH8b.png)
In this case the alias would be `None`, and the existing one refers to the world name;plotId.
Might be worth to add the other information from plot info too.

2021-08-22 17:19 UTC, NotMyFault commented on src/main/java/com/plotsquared/plot2dynmap/Main.java
> +
Both are covered within the `depend` scope in the plugin yml task. Plot2Dynmap doesn't launch without both installed.
Respectively may rename this to sth like `Plot2Dynmap` plugin instead of `Main`.

2021-08-22 22:07 UTC, NotMyFault requested changes

2021-08-22 22:07 UTC, NotMyFault commented on src/main/resources/config.yml
> +infoelement: "%key%: <span style=\"font-weight:bold;\">%values%</span><br>"
That introduces a double colon for the Flags section
![](https://i.imgur.com/urR9jnN.png)

2021-08-23 10:35 UTC, NotMyFault approved these changes

2021-08-23 21:07 UTC, SirYwell approved these changes

2021-08-23 21:07 UTC, merged